### ISSUE TITLE
Restrict line length

### ISSUE THREAD

**Issue by MitMaro** [CoursePark/eslint-config-bluedrop#7]
Should we add the [`max-length`](http://eslint.org/docs/rules/max-len) rule, and if so, with what configuration?

**Comment by dvalentiate** [comment]
probably but I will hurt someone if it is set to 80.

I do keep most of my lines under 80 but sometimes it just much better to go beyond.

120 is reasonable but I'd do something like 150.

**Comment by erinwu** [comment]
our goal here is that nobody got hurt. I like 150 as well, or at least 120.

**Comment by MitMaro** [comment]
I usually do 80 as a soft target but have a hard limit of 120. I'm not a fan of limiting to 80 as it sometimes forces new lines when they are not needed.

ESLint also has some configurations that may be useful, such as ignoring end of line comments.

I would prefer 120, but am okay with 150.

**Comment by dvalentiate** [comment]
I'd be good with 120 and ignore end of line comments in the count

**Comment by MitMaro** [comment]
I also added ignoreUrls as it seems useful if we ever have a long url to not split it up.

How does this look:

	'max-len': [
		'error',
		{
			code: 120,
			ignoreTrailingComments: true,
			ignoreUrls: true
		}
	],

**Comment by erinwu** [comment]
what do you guys think of the max-len on sql files? It seems more difficult to read if we need to force the query to a second line.

![screen shot 2016-07-11 at 12 05 21 pm copy](https://cloud.githubusercontent.com/assets/971621/16743107/b88effe8-475f-11e6-93bb-daa321b72e6c.png)

**Comment by MitMaro** [comment]
Not sure how we feel about posting query images on a public repo.

But to the issue, we don't currently check line length on sql files, so I would be okay with not enforcing it on them.

**Comment by erinwu** [comment]
haha.. I'll remove the image. Yeah. not enforcing on sql files is good.

**Comment by dvalentiate** [comment]
and it is reasonable in places to use
`// eslint-disable-line max-len`

and for blocks

```
/* eslint-disable max-len */
/* eslint-enable max-len */
```

**Comment by dvalentiate** [comment]
lets do it

**Comment by christophertrudel** [comment]
120, 80 is out because @dvalentiate might decapitate some one with his bare hands. I think 150 is too much.
